USE `PACS`;
DROP procedure IF EXISTS `GET_STATUS_DETAILS`;

DELIMITER $$
USE `PACS`$$
CREATE PROCEDURE `GET_STATUS_DETAILS` ()
READS SQL DATA
P1:BEGIN
	BEGIN
		DECLARE STATUS_DETAILS CURSOR FOR

		SELECT ST.STATUS_ID, ST.STATUS_DECRIPTION, SD.STATUS_DET_ID, SD.STATUS_DET_DESC FROM PACS.STATUS_TYPE ST, PACS.STATUS_DETAILS SD where ST.STATUS_ID=SD.STATUS_ID;

		OPEN STATUS_DETAILS;
	END;
END P1$$

DELIMITER ;

